'use client';

import { useEffect, useMemo, useState } from 'react';
import { Check, Download, Eye, FileText, Mail, RefreshCw, Search, Trash2, X, XCircle } from 'lucide-react';
import AdminShell from '@/components/admin/AdminShell';
import { Booking, formatKES, guests, safeDate, useAdminData } from '@/components/admin/useAdminData';

const statusClass: Record<string,string> = { pending:'bg-orange-50 text-orange-700', confirmed:'bg-cyan-50 text-cyan-700', completed:'bg-emerald-50 text-emerald-700', cancelled:'bg-red-50 text-red-700' };
const PAYMENT_METHODS = ['Cash','Card','Bank','Link','M-Pesa','PayPal'] as const;

export default function BookingsPage() {
  const { reservations, stats, loading, error, reload } = useAdminData();
  const [search,setSearch]=useState(''); const [status,setStatus]=useState(''); const [type,setType]=useState(''); const [selected,setSelected]=useState<Booking|null>(null); const [busy,setBusy]=useState('');
  const [notes,setNotes]=useState(''); const [paymentStatus,setPaymentStatus]=useState('unpaid'); const [total,setTotal]=useState(''); const [paymentAmount,setPaymentAmount]=useState(''); const [paymentMethod,setPaymentMethod]=useState(''); const [nationality,setNationality]=useState('');
  const [accommodationCost,setAccommodationCost]=useState(''); const [parkFees,setParkFees]=useState(''); const [guideCost,setGuideCost]=useState(''); const [transportCost,setTransportCost]=useState(''); const [mealsCost,setMealsCost]=useState(''); const [otherCosts,setOtherCosts]=useState(''); const [discount,setDiscount]=useState(''); const [tax,setTax]=useState(''); const [currency,setCurrency]=useState('KES');
  const [toast,setToast]=useState(''); const [role,setRole]=useState('staff'); const [emailType,setEmailType]=useState('quote'); const [emailSubject,setEmailSubject]=useState(''); const [emailMessage,setEmailMessage]=useState(''); const [sendingEmail,setSendingEmail]=useState(false);
  useEffect(()=>{fetch('/api/admin/session').then(r=>r.json()).then(d=>setRole(d.role==='owner'?'owner':'staff')).catch(()=>setRole('staff'))},[]);
  const filtered=useMemo(()=>reservations.filter(b=>{const q=search.toLowerCase().trim(); const text=[b.booking_ref,b.first_name,b.last_name,b.email,b.whatsapp,b.safari_name,b.nationality].join(' ').toLowerCase(); return (!q||text.includes(q))&&(!status||b.reservation_status===status)&&(!type||b.booking_type===type)}),[reservations,search,status,type]);
  useEffect(()=>{if(selected){setNotes(selected.admin_notes||'');setPaymentStatus(selected.payment_status||'unpaid');setTotal(selected.total_price==null?'':String(selected.total_price));setPaymentAmount('');setPaymentMethod(selected.payment_method||'');setNationality(selected.nationality||'');setAccommodationCost(selected.accommodation_cost==null?'':String(selected.accommodation_cost));setParkFees(selected.park_fees==null?'':String(selected.park_fees));setGuideCost(selected.guide_cost==null?'':String(selected.guide_cost));setTransportCost(selected.transport_cost==null?'':String(selected.transport_cost));setMealsCost(selected.meals_cost==null?'':String(selected.meals_cost));setOtherCosts(selected.other_costs==null?'':String(selected.other_costs));setDiscount(selected.discount==null?'':String(selected.discount));setTax(selected.tax==null?'':String(selected.tax));setCurrency(selected.currency||'KES')}},[selected]);
  // Live preview only — the invoice PDF is the authoritative recalculation
  // (lib/invoice-generator.ts reads these same fields at generation time).
  // This mirrors that same subtotal → discount → tax → total math so the
  // admin sees the effect of an edit before saving/regenerating anything.
  const costSubtotal = [accommodationCost,parkFees,guideCost,transportCost,mealsCost,otherCosts].reduce((sum,v)=>sum+(Number(v)||0),0);
  const costTotal = Math.max(0, costSubtotal - (Number(discount)||0) + (Number(tax)||0));
  function notify(s:string){setToast(s);setTimeout(()=>setToast(''),3500)}
  async function action(id:number, actionName:string, extra:Record<string,unknown>={}){setBusy(`${actionName}-${id}`);try{const r=await fetch(`/api/admin/reservations/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:actionName,...extra})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Action failed');setSelected(d.reservation||selected);if(d.url) window.open(d.url,'_blank','noopener,noreferrer'); notify(actionName==='approve'?'Booking approved':actionName==='reject'?'Booking rejected':actionName==='complete'?'Trip completed':actionName==='generate_invoice'?'Invoice generated':actionName==='generate_voucher'?'Voucher generated':'Booking updated');await reload()}catch(e){notify(e instanceof Error?e.message:'Action failed')}finally{setBusy('')}}
  async function save(){if(!selected?.id)return; const price=Number(total); if(!Number.isFinite(price)||price<0){notify('Enter a valid total price');return}setBusy('save');try{const r=await fetch(`/api/admin/reservations/${selected.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({admin_notes:notes,payment_status:paymentStatus,total_price:price,payment_method:paymentMethod||null,nationality:nationality||null,accommodation_cost:accommodationCost===''?null:Number(accommodationCost),park_fees:parkFees===''?null:Number(parkFees),guide_cost:guideCost===''?null:Number(guideCost),transport_cost:transportCost===''?null:Number(transportCost),meals_cost:mealsCost===''?null:Number(mealsCost),other_costs:otherCosts===''?null:Number(otherCosts),discount:discount===''?null:Number(discount),tax:tax===''?null:Number(tax),currency:currency||'KES'})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Save failed');setSelected(d.reservation);notify('Booking saved');await reload()}catch(e){notify(e instanceof Error?e.message:'Save failed')}finally{setBusy('')}}
  async function recordPayment(){if(!selected?.id)return;const amount=Number(paymentAmount);if(!amount||amount<0){notify('Enter a payment amount');return}await action(selected.id,'record_payment',{amount,payment_method:paymentMethod||undefined});setPaymentAmount('')}
  async function sendEmail(){if(!selected?.id)return;if(emailType==='custom'&&!emailMessage.trim()){notify('Write a message before sending');return}setSendingEmail(true);try{const r=await fetch(`/api/admin/reservations/${selected.id}/send-email`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:emailType,subject:emailSubject||undefined,message:emailMessage||undefined})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Email failed');setEmailMessage('');setEmailSubject('');notify('Email sent')}catch(e){notify(e instanceof Error?e.message:'Email failed')}finally{setSendingEmail(false)}}
  async function doc(actionName:string){if(!selected?.id)return;await action(selected.id,actionName)}
  async function resend(){if(!selected?.id)return;setBusy('resend');try{const r=await fetch(`/api/admin/reservations/${selected.id}/resend`,{method:'POST'});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Email failed');notify('Confirmation email sent')}catch(e){notify(e instanceof Error?e.message:'Email failed')}finally{setBusy('')}}
  async function remove(){if(role!=='owner'){notify('Only the owner can delete bookings');return}if(!selected?.id||!confirm('Move this reservation to the Recycle Bin? It will be recoverable for 90 days.'))return;setBusy('delete');try{const r=await fetch(`/api/admin/reservations/${selected.id}`,{method:'DELETE'});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||'Delete failed');setSelected(null);notify('Booking moved to Recycle Bin');await reload()}catch(e){notify(e instanceof Error?e.message:'Delete failed')}finally{setBusy('')}}
  function exportCsv(){if(role!=='owner'){notify('Only the owner can export bookings');return}window.location.href=`/api/admin/export?${new URLSearchParams({search,status,booking_type:type}).toString()}`}
  return <AdminShell title="Bookings & Reservations" badge={stats?.pending}>
    <div className="space-y-5">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-700">Operations</p><h2 className="mt-1 text-2xl font-bold">Bookings</h2><p className="text-sm text-slate-500">Search, approve, edit, collect payments and manage every reservation.</p></div><div className="flex gap-2"><button onClick={()=>reload()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold"><RefreshCw className="h-4 w-4"/>Refresh</button><button onClick={exportCsv} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-3 py-2 text-sm font-semibold text-white"><Download className="h-4 w-4"/>Export</button></div></div>
      {error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
      <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-[1fr_180px_180px]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, email, phone, booking #..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-cyan-500 focus:bg-white"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">All Statuses</option><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">All Types</option><option value="safari">Safari</option><option value="transfer">Transfer</option><option value="excursion">Excursion</option><option value="custom">Custom</option></select></div></div>
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b bg-slate-50 text-left text-[10px] font-bold uppercase tracking-wider text-slate-500"><th className="px-4 py-3">Reservation</th><th className="px-4 py-3">Traveler</th><th className="px-4 py-3">Package</th><th className="px-4 py-3">Travel Date</th><th className="px-4 py-3">Guests</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Payment</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={9} className="py-14 text-center text-slate-400">Loading bookings...</td></tr>:filtered.length===0?<tr><td colSpan={9} className="py-14 text-center text-slate-400">No bookings match your filters.</td></tr>:filtered.map(b=><tr key={b.id} className="border-b border-slate-100 hover:bg-slate-50/70"><td className="px-4 py-3 font-semibold text-cyan-700">{b.booking_ref||`#${b.id}`}</td><td className="px-4 py-3"><p className="font-medium">{b.first_name} {b.last_name}</p><p className="text-xs text-slate-400">{b.email||b.whatsapp||'—'}</p></td><td className="max-w-[190px] truncate px-4 py-3">{b.safari_name||'Custom Safari'}</td><td className="px-4 py-3">{safeDate(b.arrival_date)}</td><td className="px-4 py-3">{guests(b)}</td><td className="px-4 py-3 font-medium">{formatKES(b.total_price)}</td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${statusClass[b.reservation_status||'pending']||statusClass.pending}`}>{b.reservation_status||'pending'}</span></td><td className="px-4 py-3 capitalize">{b.payment_status||'unpaid'}</td><td className="px-4 py-3"><div className="flex justify-end gap-1">{b.reservation_status==='pending'&&b.id&&<><button title="Approve" onClick={()=>action(b.id!,'approve')} className="rounded-lg p-2 hover:bg-cyan-50"><Check className="h-4 w-4 text-cyan-700"/></button><button title="Reject" onClick={()=>action(b.id!,'reject')} className="rounded-lg p-2 hover:bg-red-50"><XCircle className="h-4 w-4 text-red-500"/></button></>}<button title="View" onClick={()=>setSelected(b)} className="rounded-lg p-2 hover:bg-slate-100"><Eye className="h-4 w-4 text-slate-500"/></button><button title="Email" onClick={()=>setSelected(b)} className="rounded-lg p-2 hover:bg-cyan-50"><Mail className="h-4 w-4 text-cyan-700"/></button></div></td></tr>)}</tbody></table></div><div className="border-t bg-slate-50 px-4 py-3 text-xs text-slate-500">Showing {filtered.length} of {reservations.length} loaded reservations.</div></div>
    </div>
    {selected&&<div className="fixed inset-0 z-[60] bg-slate-950/40 p-3 sm:p-6" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="ml-auto h-full w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-5 shadow-2xl sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs text-slate-400">{selected.booking_ref||`#${selected.id}`}</p><h3 className="text-xl font-bold">{selected.first_name} {selected.last_name}</h3><p className="text-sm text-slate-500">{selected.safari_name||'Custom Safari'} · {safeDate(selected.arrival_date)}</p></div><button onClick={()=>setSelected(null)} className="rounded-lg p-2 hover:bg-slate-100"><X className="h-5 w-5"/></button></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2">{[['Email',selected.email],['WhatsApp',selected.whatsapp],['Nationality',selected.nationality],['Pickup',selected.pickup_location],['Hotel',selected.hotel_name],['Guests',String(guests(selected))],['Booking type',selected.booking_type],['Created',safeDate(selected.created_at)]].map(([a,b])=><div key={String(a)} className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] uppercase tracking-wider text-slate-400">{a}</p><p className="mt-1 text-sm font-medium">{b||'—'}</p></div>)}</div>
      <div className="mt-5 rounded-xl border border-slate-200 p-4"><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs font-semibold">Total price<input value={total} onChange={e=>setTotal(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5 text-sm"/></label><label className="text-xs font-semibold">Payment status<select value={paymentStatus} onChange={e=>setPaymentStatus(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5 text-sm"><option>unpaid</option><option>partial</option><option>paid</option></select></label><label className="text-xs font-semibold">Payment method<select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5 text-sm"><option value="">Not specified</option>{PAYMENT_METHODS.map(method=><option key={method} value={method}>{method}</option>)}</select></label></div><label className="mt-3 block text-xs font-semibold">Nationality<input value={nationality} onChange={e=>setNationality(e.target.value)} placeholder="e.g. Italian, French, American..." className="mt-1 w-full rounded-lg border p-2.5 text-sm"/></label>

      {/* Itemized cost breakdown — feeds the invoice/quotation PDF directly, nothing hard-coded */}
      <div className="mt-4 rounded-xl border border-slate-200 p-4">
        <div className="flex items-center justify-between"><p className="text-sm font-semibold">Cost breakdown</p><label className="flex items-center gap-2 text-xs font-semibold text-slate-500">Currency<select value={currency} onChange={e=>setCurrency(e.target.value)} className="rounded-lg border p-1.5 text-sm"><option value="KES">KES</option><option value="USD">USD</option></select></label></div>
        <div className="mt-3 grid gap-3 sm:grid-cols-3">
          <label className="text-xs font-semibold">Accommodation<input type="number" min="0" step="0.01" value={accommodationCost} onChange={e=>setAccommodationCost(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5 text-sm"/></label>
          <label className="text-xs font-semibold">Park &amp; conservation fees<input type="number" min="0" step="0.01" value={parkFees} onChange={e=>setParkFees(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5 text-sm"/></label>
          <label className="text-xs font-semibold">Guide &amp; vehicle<input type="number" min="0" step="0.01" value={guideCost} onChange={e=>setGuideCost(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5 text-sm"/></label>
          <label className="text-xs font-semibold">Transport &amp; transfers<input type="number" min="0" step="0.01" value={transportCost} onChange={e=>setTransportCost(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5 text-sm"/></label>
          <label className="text-xs font-semibold">Meals<input type="number" min="0" step="0.01" value={mealsCost} onChange={e=>setMealsCost(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5 text-sm"/></label>
          <label className="text-xs font-semibold">Other services<input type="number" min="0" step="0.01" value={otherCosts} onChange={e=>setOtherCosts(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5 text-sm"/></label>
          <label className="text-xs font-semibold">Discount<input type="number" min="0" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5 text-sm"/></label>
          <label className="text-xs font-semibold">Tax / VAT<input type="number" min="0" step="0.01" value={tax} onChange={e=>setTax(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5 text-sm"/></label>
        </div>
        <div className="mt-3 flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-sm"><span className="text-slate-500">Subtotal</span><span className="font-semibold">{currency} {costSubtotal.toLocaleString('en-KE')}</span></div>
        <div className="mt-1 flex items-center justify-between rounded-lg bg-cyan-50 px-3 py-2 text-sm"><span className="font-semibold text-cyan-800">Recalculated total (preview)</span><span className="font-bold text-cyan-800">{currency} {costTotal.toLocaleString('en-KE')}</span></div>
        <p className="mt-2 text-[11px] text-slate-400">Save, then regenerate the invoice/quotation to apply this breakdown to the PDF. This preview mirrors the same math the PDF uses &mdash; it doesn&apos;t change &ldquo;Total price&rdquo; above on its own.</p>
      </div>

      <label className="mt-3 block text-xs font-semibold">Admin notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3} className="mt-1 w-full rounded-lg border p-2.5 text-sm"/></label><button onClick={save} disabled={busy==='save'} className="mt-3 rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Save changes</button></div>
      <div className="mt-4 rounded-xl border border-slate-200 p-4"><p className="text-sm font-semibold">Record payment</p><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input type="number" min="0.01" step="0.01" value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)} placeholder="Amount" className="rounded-lg border p-2.5 text-sm"/><select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)} className="rounded-lg border p-2.5 text-sm"><option value="">Select payment method</option>{PAYMENT_METHODS.map(method=><option key={method} value={method}>{method}</option>)}</select><button onClick={recordPayment} disabled={!paymentMethod||busy.startsWith('record_payment-')} className="rounded-lg bg-cyan-700 px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">{busy.startsWith('record_payment-')?'Recording...':'Record'}</button></div></div>
      <div className="mt-4 rounded-xl border border-slate-200 p-4"><p className="text-sm font-semibold">Customer communication</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><select value={emailType} onChange={e=>setEmailType(e.target.value)} className="rounded-lg border p-2.5 text-sm"><option value="quote">Quote</option><option value="confirmation">Confirmation</option><option value="payment_reminder">Payment reminder</option><option value="pre_departure_reminder">Pre-departure</option><option value="review_request">Review request</option><option value="custom">Custom</option></select><input value={emailSubject} onChange={e=>setEmailSubject(e.target.value)} placeholder="Optional subject" className="rounded-lg border p-2.5 text-sm"/></div><textarea value={emailMessage} onChange={e=>setEmailMessage(e.target.value)} placeholder="Optional message or use the selected template..." rows={3} className="mt-2 w-full rounded-lg border p-2.5 text-sm"/><button onClick={sendEmail} disabled={sendingEmail} className="mt-2 rounded-lg bg-cyan-700 px-4 py-2.5 text-sm font-semibold text-white">{sendingEmail?'Sending...':'Send email'}</button></div>
      <div className="mt-4 grid gap-2 sm:grid-cols-2"><button onClick={()=>doc('generate_invoice')} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-semibold"><FileText className="mr-2 inline h-4 w-4"/>Generate invoice</button><button onClick={()=>doc('generate_voucher')} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-semibold"><FileText className="mr-2 inline h-4 w-4"/>Generate voucher</button><button onClick={resend} className="rounded-xl bg-slate-900 px-3 py-2.5 text-sm font-semibold text-white"><Mail className="mr-2 inline h-4 w-4"/>Resend confirmation</button>{selected.reservation_status==='confirmed'&&<button onClick={()=>action(selected.id!,'complete')} className="rounded-xl bg-emerald-600 px-3 py-2.5 text-sm font-semibold text-white">Mark completed</button>}{selected.reservation_status==='pending'&&<button onClick={()=>action(selected.id!,'approve')} className="rounded-xl bg-cyan-700 px-3 py-2.5 text-sm font-semibold text-white">Approve booking</button>}<button onClick={remove} className="rounded-xl border border-red-200 px-3 py-2.5 text-sm font-semibold text-red-600"><Trash2 className="mr-2 inline h-4 w-4"/>Delete</button></div>
    </div></div>}
    {toast&&<div className="fixed bottom-5 right-5 z-[80] rounded-xl bg-slate-900 px-4 py-3 text-sm font-medium text-white shadow-xl">{toast}</div>}
  </AdminShell>
}
