'use client';

import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, CheckCircle2, Clock3, Download, FileCheck2, FileText, Inbox, MapPin, RefreshCw, XCircle } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { useLanguage } from '@/contexts/LanguageContext';

type Booking = { id:number; booking_ref:string; safari_name:string; arrival_date:string; adults:number; children:number; status:string; itinerary_snapshot:any };
type Invoice = { id:string; invoice_number:string; amount:number; currency:string; status:string; itinerary:any; created_at:string };
type Document = { id:string; type:string; title:string; status:string; created_at:string };
type Props = { user:{id:string;email:string|null;name:string}; initialBookings:Booking[]; initialInvoices:Invoice[]; initialDocuments:Document[] };

const copy:any = {
  en:{welcome:'Welcome',bookings:'Reservations',invoices:'Invoices',documents:'Documents Inbox',total:'Total Bookings',pending:'Pending Confirmation',pendingInvoices:'Invoices Pending',track:'Track',view:'View',download:'Download PDF',newDoc:'NEW',all:'All',voucher:'Voucher',visa_support:'Visa Support',receipt:'Receipt',itinerary:'Itinerary',invoice:'Invoice',refresh:'Refresh',empty:'Nothing here yet.',status:'Status',travellers:'travellers',date:'Travel date',amount:'Amount',created:'Created'},
  it:{welcome:'Benvenuto',bookings:'Prenotazioni',invoices:'Fatture',documents:'Posta documenti',total:'Totale prenotazioni',pending:'In attesa di conferma',pendingInvoices:'Fatture in attesa',track:'Segui',view:'Visualizza',download:'Scarica PDF',newDoc:'NUOVO',all:'Tutti',voucher:'Voucher',visa_support:'Supporto visto',receipt:'Ricevuta',itinerary:'Itinerario',invoice:'Fattura',refresh:'Aggiorna',empty:'Nessun documento.',status:'Stato',travellers:'viaggiatori',date:'Data viaggio',amount:'Importo',created:'Creato'},
  fr:{welcome:'Bienvenue',bookings:'Réservations',invoices:'Factures',documents:'Boîte de documents',total:'Réservations totales',pending:'En attente de confirmation',pendingInvoices:'Factures en attente',track:'Suivre',view:'Voir',download:'Télécharger PDF',newDoc:'NOUVEAU',all:'Tous',voucher:'Voucher',visa_support:'Support visa',receipt:'Reçu',itinerary:'Itinéraire',invoice:'Facture',refresh:'Actualiser',empty:'Aucun document.',status:'Statut',travellers:'voyageurs',date:'Date du voyage',amount:'Montant',created:'Créé'},
  es:{welcome:'Bienvenido',bookings:'Reservas',invoices:'Facturas',documents:'Bandeja de documentos',total:'Reservas totales',pending:'Pendiente de confirmación',pendingInvoices:'Facturas pendientes',track:'Seguir',view:'Ver',download:'Descargar PDF',newDoc:'NUEVO',all:'Todos',voucher:'Voucher',visa_support:'Soporte de visado',receipt:'Recibo',itinerary:'Itinerario',invoice:'Factura',refresh:'Actualizar',empty:'Aún no hay documentos.',status:'Estado',travellers:'viajeros',date:'Fecha del viaje',amount:'Importe',created:'Creado'},
  de:{welcome:'Willkommen',bookings:'Reservierungen',invoices:'Rechnungen',documents:'Dokumenten-Postfach',total:'Buchungen gesamt',pending:'Bestätigung ausstehend',pendingInvoices:'Offene Rechnungen',track:'Verfolgen',view:'Ansehen',download:'PDF herunterladen',newDoc:'NEU',all:'Alle',voucher:'Voucher',visa_support:'Visum-Unterlagen',receipt:'Beleg',itinerary:'Reiseplan',invoice:'Rechnung',refresh:'Aktualisieren',empty:'Noch keine Dokumente.',status:'Status',travellers:'Reisende',date:'Reisedatum',amount:'Betrag',created:'Erstellt'},
  ar:{welcome:'مرحباً',bookings:'الحجوزات',invoices:'الفواتير',documents:'صندوق المستندات',total:'إجمالي الحجوزات',pending:'بانتظار التأكيد',pendingInvoices:'الفواتير المعلقة',track:'تتبع',view:'عرض',download:'تنزيل PDF',newDoc:'جديد',all:'الكل',voucher:'قسيمة',visa_support:'دعم التأشيرة',receipt:'إيصال',itinerary:'خط سير الرحلة',invoice:'فاتورة',refresh:'تحديث',empty:'لا توجد مستندات بعد.',status:'الحالة',travellers:'مسافرون',date:'تاريخ الرحلة',amount:'المبلغ',created:'تاريخ الإنشاء'},
  zh:{welcome:'欢迎',bookings:'预订',invoices:'发票',documents:'文件收件箱',total:'预订总数',pending:'待确认',pendingInvoices:'待处理发票',track:'跟踪',view:'查看',download:'下载 PDF',newDoc:'新',all:'全部',voucher:'凭证',visa_support:'签证支持',receipt:'收据',itinerary:'行程',invoice:'发票',refresh:'刷新',empty:'暂无文件。',status:'状态',travellers:'旅客',date:'出行日期',amount:'金额',created:'创建时间'},
  sw:{welcome:'Karibu',bookings:'Uhifadhi',invoices:'Ankara',documents:'Kikasha cha Nyaraka',total:'Jumla ya Uhifadhi',pending:'Inasubiri Uthibitisho',pendingInvoices:'Ankara Zinazosubiri',track:'Fuatilia',view:'Tazama',download:'Pakua PDF',newDoc:'MPYA',all:'Zote',voucher:'Vocha',visa_support:'Msaada wa Visa',receipt:'Risiti',itinerary:'Ratiba',invoice:'Ankara',refresh:'Onyesha upya',empty:'Hakuna nyaraka bado.',status:'Hali',travellers:'wasafiri',date:'Tarehe ya safari',amount:'Kiasi',created:'Imeundwa'}
};

function badge(status:string){ return status==='confirmed' ? 'bg-emerald-50 text-emerald-700' : status==='cancelled' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-700'; }
function icon(status:string){ return status==='confirmed' ? <CheckCircle2 className="h-4 w-4"/> : status==='cancelled' ? <XCircle className="h-4 w-4"/> : <Clock3 className="h-4 w-4"/>; }

export default function ClientDashboard({user,initialBookings,initialInvoices,initialDocuments}:Props){
  const {locale}=useLanguage(); const c=copy[locale]||copy.en; const router=useRouter();
  const [tab,setTab]=useState<'bookings'|'invoices'|'documents'>('bookings'); const [filter,setFilter]=useState('all'); const [docs,setDocs]=useState(initialDocuments); const [selected,setSelected]=useState<Booking|null>(null); const [busy,setBusy]=useState('');
  const pending=initialBookings.filter(b=>b.status==='pending_confirmation').length;
  const pendingInvoices=initialInvoices.filter(i=>i.status==='pending').length;
  const visibleDocs=useMemo(()=>filter==='all'?docs:docs.filter(d=>d.type===filter),[docs,filter]);
  useEffect(()=>{const timer=window.setInterval(()=>router.refresh(),30000);return()=>window.clearInterval(timer)},[router]);

  async function openDoc(id:string, invoice:boolean, download:boolean){
    setBusy(id);
    try{
      const endpoint=invoice ? '/api/account/invoices/'+id : '/api/account/documents/'+id+'?view=1';
      const r=await fetch(endpoint,{cache:'no-store'}); const d=await r.json(); if(!r.ok||!d.success) throw new Error(d.error||'Document unavailable');
      if(download){const a=document.createElement('a');a.href=d.url;a.target='_blank';a.rel='noopener noreferrer';a.click()} else window.open(d.url,'_blank','noopener,noreferrer');
      if(!invoice)setDocs(prev=>prev.map(x=>x.id===id?{...x,status:'viewed'}:x));
    }catch(e){window.alert(e instanceof Error?e.message:'Document unavailable')}finally{setBusy('')}
  }

  return <div className="min-h-screen bg-slate-50">
    <header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-5 sm:px-6 lg:px-8"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-700">Bahari Asili Safaris</p><h1 className="mt-1 text-2xl font-bold text-slate-900">{c.welcome}, {user.name}</h1><p className="mt-1 text-sm text-slate-500">{user.email}</p></div><button onClick={()=>router.refresh()} className="inline-flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-sm font-semibold"><RefreshCw className="h-4 w-4"/>{c.refresh}</button></div></header>
    <main className="mx-auto max-w-7xl space-y-6 px-4 py-6 sm:px-6 lg:px-8">
      <section className="grid gap-4 sm:grid-cols-3">{[[c.total,initialBookings.length],[c.pending,pending],[c.pendingInvoices,pendingInvoices]].map(([label,value])=><div key={String(label)} className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{String(value)}</p></div>)}</section>
      <section className="rounded-2xl border bg-white shadow-sm">
        <div className="flex flex-wrap gap-2 border-b p-3"><button onClick={()=>setTab('bookings')} className={tab==='bookings'?'rounded-xl bg-cyan-700 px-4 py-2 text-sm font-semibold text-white':'rounded-xl px-4 py-2 text-sm font-semibold hover:bg-slate-100'}><CalendarDays className="mr-2 inline h-4 w-4"/>{c.bookings}</button><button onClick={()=>setTab('invoices')} className={tab==='invoices'?'rounded-xl bg-cyan-700 px-4 py-2 text-sm font-semibold text-white':'rounded-xl px-4 py-2 text-sm font-semibold hover:bg-slate-100'}><FileText className="mr-2 inline h-4 w-4"/>{c.invoices}</button><button onClick={()=>setTab('documents')} className={tab==='documents'?'rounded-xl bg-cyan-700 px-4 py-2 text-sm font-semibold text-white':'rounded-xl px-4 py-2 text-sm font-semibold hover:bg-slate-100'}><Inbox className="mr-2 inline h-4 w-4"/>{c.documents}</button></div>
        {tab==='bookings'&&<div className="divide-y">{initialBookings.length===0?<p className="p-10 text-center text-sm text-slate-500">{c.empty}</p>:initialBookings.map(b=><div key={b.id} className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-cyan-50 text-cyan-700"><MapPin className="h-5 w-5"/></div><div><p className="font-semibold">{b.itinerary_snapshot?.title||b.safari_name}</p><p className="mt-1 text-xs text-slate-500">{b.booking_ref} · {b.arrival_date} · {b.adults+b.children} {c.travellers}</p></div></div><div className="flex items-center gap-3"><span className={'inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs font-semibold '+badge(b.status)}>{icon(b.status)}{b.status.replace('_',' ')}</span><button onClick={()=>setSelected(b)} className="rounded-xl border px-3 py-2 text-sm font-semibold">{c.track}</button></div></div>)}</div>}
        {tab==='invoices'&&<div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">{c.invoice}</th><th className="px-5 py-3">Itinerary</th><th className="px-5 py-3">{c.amount}</th><th className="px-5 py-3">{c.status}</th><th className="px-5 py-3">{c.created}</th><th></th></tr></thead><tbody className="divide-y">{initialInvoices.map(i=><tr key={i.id}><td className="px-5 py-4 font-semibold text-cyan-700">{i.invoice_number}</td><td className="px-5 py-4">{i.itinerary?.name||i.itinerary?.title||'Safari'}</td><td className="px-5 py-4 font-semibold">{i.currency} {Number(i.amount||0).toLocaleString()}</td><td className="px-5 py-4 capitalize">{i.status==='pending'?'pending to be confirmed':i.status}</td><td className="px-5 py-4 text-slate-500">{new Date(i.created_at).toLocaleDateString()}</td><td className="px-5 py-4 text-right"><button disabled={busy===i.id} onClick={()=>openDoc(i.id,true,false)} className="rounded-xl bg-cyan-700 px-3 py-2 text-xs font-semibold text-white"><Download className="mr-1 inline h-3.5 w-3.5"/>{c.download}</button></td></tr>)}</tbody></table></div>}
        {tab==='documents'&&<div><div className="flex flex-wrap gap-2 border-b p-4">{['all','invoice','voucher','visa_support','receipt','itinerary'].map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?'rounded-lg bg-slate-900 px-3 py-1.5 text-xs font-semibold text-white':'rounded-lg bg-slate-100 px-3 py-1.5 text-xs font-semibold'}>{x==='all'?c.all:(c[x]||x)}</button>)}</div><div className="divide-y">{visibleDocs.length===0?<p className="p-10 text-center text-sm text-slate-500">{c.empty}</p>:visibleDocs.map(d=><div key={d.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100"><FileCheck2 className="h-5 w-5 text-cyan-700"/></div><div><p className="font-semibold">{d.title}</p><p className="mt-1 text-xs text-slate-500">{c[d.type]||d.type} · {new Date(d.created_at).toLocaleDateString()}</p></div></div><div className="flex items-center gap-2"><span className={d.status==='sent'?'rounded-full bg-amber-50 px-2.5 py-1 text-[10px] font-semibold text-amber-700':'rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold text-slate-500'}>{d.status==='sent'?c.newDoc:c.view}</span><button disabled={busy===d.id} onClick={()=>openDoc(d.id,false,false)} className="rounded-xl border px-3 py-2 text-xs font-semibold">{c.view}</button><button disabled={busy===d.id} onClick={()=>openDoc(d.id,false,true)} className="rounded-xl bg-cyan-700 px-3 py-2 text-xs font-semibold text-white">{c.download}</button></div></div>)}</div></div>}
      </section>
    </main>
    {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs text-slate-500">{selected.booking_ref}</p><h2 className="mt-1 text-xl font-bold">{selected.itinerary_snapshot?.title||selected.safari_name}</h2></div><button onClick={()=>setSelected(null)} className="rounded-lg p-2 hover:bg-slate-100">×</button></div><div className="mt-5 space-y-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{c.status}</p><p className="mt-1 flex items-center gap-2 font-semibold capitalize">{icon(selected.status)}{selected.status.replace('_',' ')}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{c.date}</p><p className="mt-1 font-semibold">{selected.arrival_date}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{c.travellers}</p><p className="mt-1 font-semibold">{selected.adults+selected.children}</p></div></div></div></div>}
  </div>
}
