'use client';
import { ArrowRight, MessageCircle, Phone } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';
import { trackConversion } from '@/components/Analytics';
import { getHomeLanding } from '@/lib/home-landing-i18n';
import { PHONE_TEL, whatsappHref } from '@/lib/contact-info';
export default function FinalCtaSection({ onBook }: { onBook: () => void }) {
 const {locale}=useLanguage(); const e=getHomeLanding(locale);
 return <section className="bg-ink py-28 lg:py-44"><div className="editorial-shell"><h2 className="font-editorial text-6xl leading-[0.9] text-white sm:text-8xl">{e.final.title}</h2><p className="mt-7 max-w-xl font-grotesk text-base leading-7 text-white/70">{e.final.based}</p><div className="mt-12 flex flex-col justify-center gap-3 sm:flex-row"><button onClick={onBook} className="inline-flex items-center justify-center gap-2 rounded-sm bg-sun px-7 py-3.5 font-mono-editorial text-[11px] font-semibold uppercase tracking-[0.08em] text-ink hover:brightness-105"><ArrowRight className="h-4 w-4"/>{e.final.plan}</button><a href={whatsappHref(e.whatsappMessage)} target="_blank" rel="noopener noreferrer" onClick={()=>trackConversion('whatsapp_clicked',{location:'final_cta'})} className="inline-flex items-center justify-center gap-2 rounded-sm border border-white/30 px-7 py-3.5 font-mono-editorial text-[11px] font-semibold uppercase tracking-[0.08em] text-white hover:bg-white/10"><MessageCircle className="h-4 w-4"/>{e.final.whatsapp}</a><a href={`tel:${PHONE_TEL}`} onClick={()=>trackConversion('phone_clicked',{location:'final_cta'})} className="inline-flex items-center justify-center gap-2 rounded-lg border border-white/35 px-7 py-3.5 font-poppins text-sm font-semibold text-white hover:bg-white/10"><Phone className="h-4 w-4"/>{e.final.call}</a></div></div></section>;
}