"use client";
import {useEffect,useRef,useState} from "react";
import type {Stop} from "@/lib/kenya-safari-locations";
type Props={stops:Stop[];safariTitle:string;activeDay:number|null;onSelectDay:(day:number|null)=>void};
declare global{interface Window{L?:any}}
const BRAND="#0E7482";
export default function SafariRouteMap({stops,safariTitle,activeDay,onSelectDay}:Props){const element=useRef<HTMLDivElement|null>(null),map=useRef<any>(null),markers=useRef<Record<number,any>>({}),route=useRef<any>(null);const[ready,setReady]=useState(false),[error,setError]=useState(false);
useEffect(()=>{let cancelled=false;const init=()=>{if(cancelled||!element.current||!window.L)return;const L=window.L;map.current=L.map(element.current,{scrollWheelZoom:false}).setView([-0.8,37.8],6);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',maxZoom:18}).addTo(map.current);stops.forEach(stop=>{const icon=L.divIcon({className:"bahari-route-pin-wrap",html:`<span class="bahari-route-pin" data-day="${stop.day}">${stop.day}</span>`,iconSize:[34,34],iconAnchor:[17,17]});const marker=L.marker(stop.coords,{icon}).addTo(map.current).bindPopup(`<strong>Day ${stop.day}: ${escapeHtml(stop.title)}</strong><br/>${escapeHtml(stop.location)}<br/><button type="button" data-select-day="${stop.day}" style="margin-top:8px;color:${BRAND};font-weight:600">View this day</button>`);marker.on("click",()=>onSelectDay(stop.day));markers.current[stop.day]=marker;});const points=stops.map(s=>s.coords);if(points.length>1){route.current=L.polyline(points,{color:BRAND,weight:4,opacity:.8}).addTo(map.current);map.current.fitBounds(route.current.getBounds(),{padding:[28,28],maxZoom:7});}map.current.on("popupopen",(e:any)=>{const node=e.popup.getElement()?.querySelector("[data-select-day]");node?.addEventListener("click",()=>onSelectDay(Number(node.getAttribute("data-select-day"))));});setReady(true);setTimeout(()=>map.current?.invalidateSize(),100);};function escapeHtml(s:string){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));}const css=document.createElement("link");css.rel="stylesheet";css.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";css.dataset.bahariLeaflet="true";if(!document.querySelector('link[data-bahari-leaflet]'))document.head.appendChild(css);if(window.L)init();else{let script=document.querySelector<HTMLScriptElement>('script[data-bahari-leaflet]');if(!script){script=document.createElement("script");script.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";script.async=true;script.dataset.bahariLeaflet="true";document.body.appendChild(script);}script.addEventListener("load",init);script.addEventListener("error",()=>setError(true));}return()=>{cancelled=true;map.current?.remove();map.current=null;markers.current={};};},[stops,onSelectDay]);
useEffect(()=>{if(!map.current)return;if(activeDay==null){if(route.current)map.current.fitBounds(route.current.getBounds(),{padding:[28,28],maxZoom:7});return;}const marker=markers.current[activeDay];if(marker){map.current.flyTo(marker.getLatLng(),8,{duration:.6});marker.openPopup();}},[activeDay]);
return <div className="overflow-hidden rounded-2xl border border-border bg-white shadow-card"><style jsx global>{`.bahari-route-pin-wrap{background:transparent;border:0}.bahari-route-pin{display:flex;width:34px;height:34px;align-items:center;justify-content:center;border:3px solid white;border-radius:999px;background:${BRAND};color:white;font:700 13px ui-sans-serif,system-ui;box-shadow:0 2px 8px #0003}.bahari-route-pin[data-day="${activeDay}"]{background:#FF7A00;transform:scale(1.2)}`}</style><div className="relative"><div ref={element} role="application" aria-label={`Interactive route map for ${safariTitle}`} className="h-[360px] w-full sm:h-[470px]"/>{!ready&&!error&&<div className="absolute inset-0 flex items-center justify-center bg-sand-50/90 text-sm text-muted-foreground" role="status">Loading interactive route map…</div>}{error&&<div className="absolute inset-0 flex items-center justify-center bg-sand-50 p-6 text-center text-sm text-muted-foreground">The map could not load. The itinerary remains available below.</div>}</div><div className="flex flex-wrap items-center gap-x-5 gap-y-2 border-t border-border px-4 py-3 text-xs text-muted-foreground"><span>● Numbered pins are itinerary days</span><span>Map tiles © OpenStreetMap contributors</span></div></div>;}
