export interface DestinationActivity { id:string; destination:string; name:string; description:string; duration:string; level:'Easy'|'Moderate'|'Active'; image:string; }

const image='/images/excursions/love-island.jpg';
export const destinationActivities: DestinationActivity[] = [
{id:'samburu-game-drive',destination:'samburu',name:'Samburu Wildlife Game Drive',description:'Track the Samburu Special Five, elephants, big cats and dry-country wildlife along the Ewaso Ng’iro River.',duration:'Half or full day',level:'Easy',image:'/images/safaris/safari-zazu.jpg'},
{id:'samburu-cultural',destination:'samburu',name:'Samburu Cultural Visit',description:'Meet local Samburu communities and learn about pastoral traditions, crafts and daily life.',duration:'2–3 hours',level:'Easy',image},
{id:'mount-kenya-forest',destination:'mount-kenya',name:'Mount Kenya Forest Walk',description:'Explore montane forest with a local guide, looking for primates, birds and changing highland vegetation.',duration:'2–4 hours',level:'Moderate',image:'/images/safaris/safari-twiga.jpg'},
{id:'mount-kenya-moorland',destination:'mount-kenya',name:'Mount Kenya Moorland Trek',description:'Walk higher into open moorland for dramatic volcanic scenery and alpine plants.',duration:'Half or full day',level:'Active',image:'/images/safaris/safari-3day-amboseli.jpg'},
{id:'serengeti-game-drive',destination:'serengeti',name:'Serengeti Game Drive',description:'Follow wildlife across the plains with specialist guiding focused on predators and seasonal movements.',duration:'Half or full day',level:'Easy',image:'/images/safaris/safari-mufasa.jpg'},
{id:'serengeti-balloon',destination:'serengeti',name:'Serengeti Balloon Safari',description:'Optional sunrise balloon experience over the plains, subject to operator availability and weather.',duration:'Half day',level:'Easy',image:'/images/safaris/safari-sarabi.jpg'},
{id:'ngorongoro-crater',destination:'ngorongoro',name:'Ngorongoro Crater Game Drive',description:'Descend into the caldera for concentrated wildlife viewing among grasslands, wetlands and woodland.',duration:'Full day',level:'Easy',image:'/images/safaris/safari-tembo.jpg'},
{id:'ngorongoro-maasai',destination:'ngorongoro',name:'Maasai Community Experience',description:'Visit a local Maasai community through a responsible cultural programme and learn about pastoral life.',duration:'2–3 hours',level:'Easy',image:'/images/safaris/safari-rafiki.jpg'},
{id:'tarangire-game-drive',destination:'tarangire',name:'Tarangire Game Drive',description:'Search for elephants and other wildlife among giant baobabs and seasonal water sources.',duration:'Half or full day',level:'Easy',image:'/images/safaris/safari-sarabi.jpg'},
{id:'tarangire-walking',destination:'tarangire',name:'Guided Nature Walk',description:'Where permitted, explore the ecosystem on foot with a qualified guide and discover tracks, plants and smaller wildlife.',duration:'2–3 hours',level:'Moderate',image:'/images/safaris/safari-twiga.jpg'},
{id:'zanzibar-stone-town',destination:'zanzibar',name:'Stone Town Heritage Walk',description:'Discover Swahili architecture, historic lanes, markets, waterfront landmarks and Zanzibar’s trading history.',duration:'2–3 hours',level:'Easy',image:'/images/excursions/gede-ruins.jpg'},
{id:'zanzibar-spice',destination:'zanzibar',name:'Spice Farm Experience',description:'Taste and learn about cloves, cinnamon, vanilla and other crops that shaped Zanzibar’s spice trade.',duration:'2–3 hours',level:'Easy',image:'/images/excursions/dabaso-village-tour.jpg'},
{id:'queen-kazinga',destination:'queen-elizabeth',name:'Kazinga Channel Boat Safari',description:'Cruise between Lake Edward and Lake George for hippos, crocodiles, elephants and waterbirds.',duration:'2–3 hours',level:'Easy',image:'/images/excursions/blue-safari-mida-creek.jpg'},
{id:'queen-game-drive',destination:'queen-elizabeth',name:'Queen Elizabeth Game Drive',description:'Explore savannah and crater-lake country for elephants, buffalo, antelope and predators.',duration:'Half or full day',level:'Easy',image:'/images/safaris/safari-zazu.jpg'},
{id:'bwindi-gorilla',destination:'bwindi',name:'Mountain Gorilla Trekking',description:'A guided forest trek to observe a habituated gorilla family under strict conservation and permit rules.',duration:'Half or full day',level:'Active',image:'/images/safaris/safari-rafiki.jpg'},
{id:'bwindi-birding',destination:'bwindi',name:'Bwindi Forest Birding',description:'Explore one of East Africa’s exceptional montane forests with a specialist guide focused on endemic and Albertine Rift birds.',duration:'2–4 hours',level:'Moderate',image:'/images/safaris/safari-tumbili.jpg'},
{id:'murchison-nile',destination:'murchison-falls',name:'Nile Boat Safari',description:'Cruise toward the base of Murchison Falls for hippos, crocodiles, elephants and abundant waterbirds.',duration:'2–3 hours',level:'Easy',image:'/images/excursions/blue-safari-sardegna-island.jpg'},
{id:'murchison-game-drive',destination:'murchison-falls',name:'Murchison Falls Game Drive',description:'Explore the park’s northern savannah for giraffe, elephant, buffalo, antelope and predators.',duration:'Half or full day',level:'Easy',image:'/images/safaris/safari-mufasa.jpg'},
{id:'akagera-game-drive',destination:'akagera',name:'Akagera Game Drive',description:'Search Rwanda’s recovering savannah ecosystem for elephants, buffalo, giraffe, zebra and predators.',duration:'Half or full day',level:'Easy',image:'/images/safaris/safari-nala-taita.jpg'},
{id:'akagera-ihema',destination:'akagera',name:'Lake Ihema Boat Safari',description:'Explore papyrus wetlands by boat for hippos, crocodiles and some of Rwanda’s best wetland birdlife.',duration:'2–3 hours',level:'Easy',image:'/images/excursions/mangrove-canoe-mida-creek.jpg'},
];

export function getActivitiesForDestination(slug:string){ return destinationActivities.filter(a=>a.destination===slug); }
