import type { Locale } from './i18n';

export const SUPPORTED_LOCALES: Locale[] = ['en','it','fr','es','de','ar','zh','sw'];

export function normalizeLocale(value: unknown): Locale {
  return SUPPORTED_LOCALES.includes(value as Locale) ? value as Locale : 'en';
}

export const invoiceLabels: Record<Locale, Record<string, string>> = {
  en: { invoice:'INVOICE', bookingReference:'BOOKING REFERENCE', status:'Status', confirmed:'CONFIRMED', pending:'PENDING QUOTATION', clientDetails:'CLIENT DETAILS', fullName:'Full Name', email:'Email', whatsapp:'WhatsApp', nationality:'Nationality', guests:'Guests', adults:'Adults', children:'Children', childrenAges:'Children Ages', travelDetails:'TRAVEL DETAILS', safariTour:'Safari / Tour', arrivalDate:'Arrival Date', departureDate:'Departure Date', parks:'Parks / Destinations', specialRequests:'Special Requests', costBreakdown:'COST BREAKDOWN', accommodation:'Accommodation', parkFees:'Park Fees & Permits', guide:'Guide & Vehicle', transport:'Transport & Transfers', meals:'Meals & Catering', other:'Other Services', subtotal:'Subtotal', discount:'Discount', tax:'Tax & Service Charge', total:'TOTAL INVOICE', important:'IMPORTANT INFORMATION', terms:(['This invoice is issued for safari services booked with Bahari Asili Safaris.','Availability and final services remain subject to confirmation.','Please keep this invoice for your records and present it when requested.','Travel insurance is recommended for all guests.'] as any), confirm:'To confirm or ask questions, reply to this email or WhatsApp us at +254 101 923 355', questions:'Questions? Email: sheddymae02@gmail.com', founded:'Founded by Shadrack Safari' },
  it: { invoice:'FATTURA', bookingReference:'RIFERIMENTO PRENOTAZIONE', status:'Stato', confirmed:'CONFERMATA', pending:'PREVENTIVO IN ATTESA', clientDetails:'DATI DEL CLIENTE', fullName:'Nome completo', email:'Email', whatsapp:'WhatsApp', nationality:'Nazionalità', guests:'Ospiti', adults:'Adulti', children:'Bambini', childrenAges:'Età dei bambini', travelDetails:'DETTAGLI DEL VIAGGIO', safariTour:'Safari / Tour', arrivalDate:'Data di arrivo', departureDate:'Data di partenza', parks:'Parchi / Destinazioni', specialRequests:'Richieste speciali', costBreakdown:'DETTAGLIO DEI COSTI', accommodation:'Alloggio', parkFees:'Parchi e permessi', guide:'Guida e veicolo', transport:'Trasporti e trasferimenti', meals:'Pasti e catering', other:'Altri servizi', subtotal:'Subtotale', discount:'Sconto', tax:'Tasse e costi di servizio', total:'TOTALE FATTURA', important:'INFORMAZIONI IMPORTANTI', terms:(['Questa fattura riguarda i servizi safari prenotati con Bahari Asili Safaris.','La disponibilità e i servizi finali restano soggetti a conferma.','Conservate questa fattura per i vostri archivi.','Si raccomanda un’assicurazione di viaggio per tutti gli ospiti.'] as any), confirm:'Per confermare o fare domande, rispondete a questa email o scrivete su WhatsApp +254 101 923 355', questions:'Domande? Email: sheddymae02@gmail.com', founded:'Fondata da Shadrack Safari' },
  fr: { invoice:'FACTURE', bookingReference:'RÉFÉRENCE DE RÉSERVATION', status:'Statut', confirmed:'CONFIRMÉE', pending:'DEVIS EN ATTENTE', clientDetails:'INFORMATIONS CLIENT', fullName:'Nom complet', email:'Email', whatsapp:'WhatsApp', nationality:'Nationalité', guests:'Voyageurs', adults:'Adultes', children:'Enfants', childrenAges:'Âges des enfants', travelDetails:'DÉTAILS DU VOYAGE', safariTour:'Safari / Circuit', arrivalDate:'Date d’arrivée', departureDate:'Date de départ', parks:'Parcs / Destinations', specialRequests:'Demandes particulières', costBreakdown:'DÉTAIL DES COÛTS', accommodation:'Hébergement', parkFees:'Parcs et permis', guide:'Guide et véhicule', transport:'Transport et transferts', meals:'Repas', other:'Autres services', subtotal:'Sous-total', discount:'Remise', tax:'Taxes et frais de service', total:'TOTAL FACTURE', important:'INFORMATIONS IMPORTANTES', terms:(['Cette facture concerne les services safari réservés auprès de Bahari Asili Safaris.','La disponibilité et les services finaux restent soumis à confirmation.','Veuillez conserver cette facture pour vos dossiers.','Une assurance voyage est recommandée pour tous les voyageurs.'] as any), confirm:'Pour confirmer ou poser une question, répondez à cet email ou écrivez sur WhatsApp +254 101 923 355', questions:'Questions ? Email : sheddymae02@gmail.com', founded:'Fondée par Shadrack Safari' },
  es: { invoice:'FACTURA', bookingReference:'REFERENCIA DE RESERVA', status:'Estado', confirmed:'CONFIRMADA', pending:'PRESUPUESTO PENDIENTE', clientDetails:'DATOS DEL CLIENTE', fullName:'Nombre completo', email:'Correo electrónico', whatsapp:'WhatsApp', nationality:'Nacionalidad', guests:'Viajeros', adults:'Adultos', children:'Niños', childrenAges:'Edades de los niños', travelDetails:'DETALLES DEL VIAJE', safariTour:'Safari / Tour', arrivalDate:'Fecha de llegada', departureDate:'Fecha de salida', parks:'Parques / Destinos', specialRequests:'Solicitudes especiales', costBreakdown:'DESGLOSE DE COSTES', accommodation:'Alojamiento', parkFees:'Parques y permisos', guide:'Guía y vehículo', transport:'Transporte y traslados', meals:'Comidas', other:'Otros servicios', subtotal:'Subtotal', discount:'Descuento', tax:'Impuestos y servicio', total:'TOTAL FACTURA', important:'INFORMACIÓN IMPORTANTE', terms:(['Esta factura corresponde a los servicios de safari reservados con Bahari Asili Safaris.','La disponibilidad y los servicios finales están sujetos a confirmación.','Conserve esta factura para sus registros.','Se recomienda un seguro de viaje para todos los viajeros.'] as any), confirm:'Para confirmar o hacer preguntas, responda a este correo o escríbanos por WhatsApp +254 101 923 355', questions:'¿Preguntas? Email: sheddymae02@gmail.com', founded:'Fundada por Shadrack Safari' },
  de: { invoice:'RECHNUNG', bookingReference:'BUCHUNGSREFERENZ', status:'Status', confirmed:'BESTÄTIGT', pending:'ANGEBOT AUSSTEHEND', clientDetails:'KUNDENDATEN', fullName:'Vollständiger Name', email:'E-Mail', whatsapp:'WhatsApp', nationality:'Nationalität', guests:'Gäste', adults:'Erwachsene', children:'Kinder', childrenAges:'Alter der Kinder', travelDetails:'REISEDETAILS', safariTour:'Safari / Tour', arrivalDate:'Anreisedatum', departureDate:'Abreisedatum', parks:'Parks / Reiseziele', specialRequests:'Besondere Wünsche', costBreakdown:'KOSTENAUFSTELLUNG', accommodation:'Unterkunft', parkFees:'Parkgebühren und Genehmigungen', guide:'Guide und Fahrzeug', transport:'Transport und Transfers', meals:'Mahlzeiten', other:'Weitere Leistungen', subtotal:'Zwischensumme', discount:'Rabatt', tax:'Steuern und Servicegebühr', total:'RECHNUNGSSUMME', important:'WICHTIGE INFORMATIONEN', terms:(['Diese Rechnung betrifft Safari-Leistungen von Bahari Asili Safaris.','Verfügbarkeit und endgültige Leistungen bleiben vorbehaltlich der Bestätigung.','Bitte bewahren Sie diese Rechnung für Ihre Unterlagen auf.','Eine Reiseversicherung wird empfohlen.'] as any), confirm:'Zur Bestätigung oder bei Fragen antworten Sie auf diese E-Mail oder schreiben Sie WhatsApp +254 101 923 355', questions:'Fragen? E-Mail: sheddymae02@gmail.com', founded:'Gegründet von Shadrack Safari' },
  ar: { invoice:'الفاتورة', bookingReference:'مرجع الحجز', status:'الحالة', confirmed:'مؤكد', pending:'عرض سعر قيد الانتظار', clientDetails:'بيانات العميل', fullName:'الاسم الكامل', email:'البريد الإلكتروني', whatsapp:'واتساب', nationality:'الجنسية', guests:'الضيوف', adults:'البالغون', children:'الأطفال', childrenAges:'أعمار الأطفال', travelDetails:'تفاصيل الرحلة', safariTour:'السفاري / الجولة', arrivalDate:'تاريخ الوصول', departureDate:'تاريخ المغادرة', parks:'المتنزهات / الوجهات', specialRequests:'طلبات خاصة', costBreakdown:'تفاصيل التكلفة', accommodation:'الإقامة', parkFees:'رسوم المتنزهات والتصاريح', guide:'المرشد والمركبة', transport:'النقل والتنقلات', meals:'الوجبات', other:'خدمات أخرى', subtotal:'المجموع الفرعي', discount:'الخصم', tax:'الضرائب ورسوم الخدمة', total:'إجمالي الفاتورة', important:'معلومات مهمة', terms:(['هذه الفاتورة خاصة بخدمات السفاري المحجوزة مع Bahari Asili Safaris.','تخضع التوافر والخدمات النهائية للتأكيد.','يرجى الاحتفاظ بهذه الفاتورة لسجلاتكم.','يوصى بتأمين السفر لجميع الضيوف.'] as any), confirm:'للتأكيد أو لطرح الأسئلة، يمكنكم الرد على هذا البريد أو مراسلتنا عبر واتساب +254 101 923 355', questions:'للأسئلة: sheddymae02@gmail.com', founded:'تأسست بواسطة شدرَاك سفاري' },
  zh: { invoice:'发票', bookingReference:'预订编号', status:'状态', confirmed:'已确认', pending:'报价待确认', clientDetails:'客户信息', fullName:'姓名', email:'电子邮箱', whatsapp:'WhatsApp', nationality:'国籍', guests:'客人', adults:'成人', children:'儿童', childrenAges:'儿童年龄', travelDetails:'行程信息', safariTour:'Safari / 行程', arrivalDate:'抵达日期', departureDate:'离开日期', parks:'公园 / 目的地', specialRequests:'特殊要求', costBreakdown:'费用明细', accommodation:'住宿', parkFees:'公园门票及许可', guide:'导游及车辆', transport:'交通及接送', meals:'餐饮', other:'其他服务', subtotal:'小计', discount:'折扣', tax:'税费及服务费', total:'发票总额', important:'重要信息', terms:(['本发票适用于 Bahari Asili Safaris 提供的已预订 Safari 服务。','最终可用性及服务须经确认。','请保存此发票以备记录。','建议所有客人购买旅行保险。'] as any), confirm:'如需确认或咨询，请回复此邮件或通过 WhatsApp +254 101 923 355 联系我们', questions:'咨询邮箱：sheddymae02@gmail.com', founded:'Shadrack Safari 创立' },
  sw: { invoice:'ANKARA', bookingReference:'NAMBARI YA BOOKING', status:'Hali', confirmed:'IMETHIBITISHWA', pending:'NUKUU INASUBIRI', clientDetails:'TAARIFA ZA MTEJA', fullName:'Jina kamili', email:'Barua pepe', whatsapp:'WhatsApp', nationality:'Utaifa', guests:'Wasafiri', adults:'Watu wazima', children:'Watoto', childrenAges:'Umri wa watoto', travelDetails:'TAARIFA ZA SAFARI', safariTour:'Safari / Ziara', arrivalDate:'Tarehe ya kuwasili', departureDate:'Tarehe ya kuondoka', parks:'Hifadhi / Maeneo', specialRequests:'Maombi maalum', costBreakdown:'MAELEZO YA GHARAMA', accommodation:'Malazi', parkFees:'Ada za hifadhi na vibali', guide:'Mwongoza na gari', transport:'Usafiri na transfers', meals:'Milo', other:'Huduma nyingine', subtotal:'Jumla ndogo', discount:'Punguzo', tax:'Kodi na ada ya huduma', total:'JUMLA YA ANKARA', important:'TAARIFA MUHIMU', terms:(['Ankara hii ni ya huduma za safari zilizowekwa na Bahari Asili Safaris.','Upatikanaji na huduma za mwisho zinategemea uthibitisho.','Tafadhali hifadhi ankara hii kwa kumbukumbu zako.','Bima ya safari inapendekezwa kwa wageni wote.'] as any), confirm:'Kuthibitisha au kuuliza swali, jibu barua pepe hii au WhatsApp +254 101 923 355', questions:'Maswali? Email: sheddymae02@gmail.com', founded:'Ilianzishwa na Shadrack Safari' },
};

export function formatLocaleDate(value: string | undefined | null, locale: Locale): string {
  if (!value) return '—';
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return value;
  const intl = locale === 'zh' ? 'zh-CN' : locale === 'ar' ? 'ar' : locale === 'sw' ? 'sw-KE' : `${locale}-${locale === 'de' ? 'DE' : locale === 'fr' ? 'FR' : locale === 'it' ? 'IT' : locale === 'es' ? 'ES' : 'GB'}`;
  return d.toLocaleDateString(intl, { year: 'numeric', month: 'long', day: 'numeric' });
}
