import type { Safari } from '@/lib/tours-data';

export type SafariLocale = 'en' | 'it' | 'fr' | 'es' | 'de' | 'ar' | 'zh' | 'sw';

type LocalizedSafari = Safari;

const destinationNames: Record<SafariLocale, Record<string, string>> = {
  en: {},
  it: { 'Tsavo East': 'Tsavo Est', 'Tsavo West': 'Tsavo Ovest', 'Amboseli': 'Amboseli', 'Taita Hills': 'Taita Hills', 'Masai Mara': 'Masai Mara', 'Samburu': 'Samburu', 'Lake Nakuru': 'Lago Nakuru', 'Lake Naivasha': 'Lago Naivasha', 'Hell’s Gate': 'Hell’s Gate', 'Mount Kenya': 'Monte Kenya', 'Serengeti': 'Serengeti', 'Ngorongoro': 'Ngorongoro', 'Tarangire': 'Tarangire', 'Zanzibar': 'Zanzibar', 'Queen Elizabeth': 'Queen Elizabeth', 'Bwindi': 'Bwindi', 'Murchison Falls': 'Murchison Falls', 'Akagera': 'Akagera' },
  fr: { 'Tsavo East': 'Tsavo Est', 'Tsavo West': 'Tsavo Ouest', 'Amboseli': 'Amboseli', 'Taita Hills': 'Collines de Taita', 'Masai Mara': 'Masai Mara', 'Samburu': 'Samburu', 'Lake Nakuru': 'Lac Nakuru', 'Lake Naivasha': 'Lac Naivasha', 'Hell’s Gate': 'Hell’s Gate', 'Mount Kenya': 'Mont Kenya', 'Serengeti': 'Serengeti', 'Ngorongoro': 'Ngorongoro', 'Tarangire': 'Tarangire', 'Zanzibar': 'Zanzibar', 'Queen Elizabeth': 'Queen Elizabeth', 'Bwindi': 'Bwindi', 'Murchison Falls': 'Murchison Falls', 'Akagera': 'Akagera' },
  es: { 'Tsavo East': 'Tsavo Este', 'Tsavo West': 'Tsavo Oeste', 'Amboseli': 'Amboseli', 'Taita Hills': 'Colinas de Taita', 'Masai Mara': 'Masai Mara', 'Samburu': 'Samburu', 'Lake Nakuru': 'Lago Nakuru', 'Lake Naivasha': 'Lago Naivasha', 'Hell’s Gate': 'Hell’s Gate', 'Mount Kenya': 'Monte Kenia', 'Serengeti': 'Serengeti', 'Ngorongoro': 'Ngorongoro', 'Tarangire': 'Tarangire', 'Zanzibar': 'Zanzíbar', 'Queen Elizabeth': 'Queen Elizabeth', 'Bwindi': 'Bwindi', 'Murchison Falls': 'Murchison Falls', 'Akagera': 'Akagera' },
  de: { 'Tsavo East': 'Tsavo Ost', 'Tsavo West': 'Tsavo West', 'Amboseli': 'Amboseli', 'Taita Hills': 'Taita-Hügel', 'Masai Mara': 'Masai Mara', 'Samburu': 'Samburu', 'Lake Nakuru': 'Nakuru-See', 'Lake Naivasha': 'Naivasha-See', 'Hell’s Gate': 'Hell’s Gate', 'Mount Kenya': 'Mount Kenya', 'Serengeti': 'Serengeti', 'Ngorongoro': 'Ngorongoro', 'Tarangire': 'Tarangire', 'Zanzibar': 'Sansibar', 'Queen Elizabeth': 'Queen Elizabeth', 'Bwindi': 'Bwindi', 'Murchison Falls': 'Murchison Falls', 'Akagera': 'Akagera' },
  ar: { 'Tsavo East': 'تسافو الشرقية', 'Tsavo West': 'تسافو الغربية', 'Amboseli': 'أمبوسيلي', 'Taita Hills': 'تلال تايتا', 'Masai Mara': 'ماساي مارا', 'Samburu': 'سامبورو', 'Lake Nakuru': 'بحيرة ناكورو', 'Lake Naivasha': 'بحيرة نيفاشا', 'Hell’s Gate': 'بوابة الجحيم', 'Mount Kenya': 'جبل كينيا', 'Serengeti': 'سيرينغيتي', 'Ngorongoro': 'نغورونغورو', 'Tarangire': 'تارانغيري', 'Zanzibar': 'زنجبار', 'Queen Elizabeth': 'كوين إليزابيث', 'Bwindi': 'بويندي', 'Murchison Falls': 'شلالات مورشيسون', 'Akagera': 'أكا جيرا' },
  zh: { 'Tsavo East': '察沃东部', 'Tsavo West': '察沃西部', 'Amboseli': '安博塞利', 'Taita Hills': '泰塔山', 'Masai Mara': '马赛马拉', 'Samburu': '桑布鲁', 'Lake Nakuru': '纳库鲁湖', 'Lake Naivasha': '奈瓦沙湖', 'Hell’s Gate': '地狱之门', 'Mount Kenya': '肯尼亚山', 'Serengeti': '塞伦盖蒂', 'Ngorongoro': '恩戈罗恩戈罗', 'Tarangire': '塔兰吉雷', 'Zanzibar': '桑给巴尔', 'Queen Elizabeth': '伊丽莎白女王国家公园', 'Bwindi': '布温迪', 'Murchison Falls': '默奇森瀑布', 'Akagera': '阿卡盖拉' },
  sw: { 'Tsavo East': 'Tsavo Mashariki', 'Tsavo West': 'Tsavo Magharibi', 'Amboseli': 'Amboseli', 'Taita Hills': 'Milima ya Taita', 'Masai Mara': 'Masai Mara', 'Samburu': 'Samburu', 'Lake Nakuru': 'Ziwa Nakuru', 'Lake Naivasha': 'Ziwa Naivasha', 'Hell’s Gate': 'Hell’s Gate', 'Mount Kenya': 'Mlima Kenya', 'Serengeti': 'Serengeti', 'Ngorongoro': 'Ngorongoro', 'Tarangire': 'Tarangire', 'Zanzibar': 'Zanzibar', 'Queen Elizabeth': 'Queen Elizabeth', 'Bwindi': 'Bwindi', 'Murchison Falls': 'Maporomoko ya Murchison', 'Akagera': 'Akagera' }
};

const copy: Record<Exclude<SafariLocale, 'en'>, { safari: string; days: string; nights: string; morning: string; afternoon: string; overnight: string; packing: string[]; included: string[]; excluded: string[]; why: string; }> = {
  it: { safari: 'Safari', days: 'giorni', nights: 'notte', morning: 'Mattina', afternoon: 'Pomeriggio', overnight: 'Pernottamento', packing: ['Protezione solare ad alta protezione', 'Cappello a tesa larga', 'Repellente per insetti', 'Abbigliamento leggero dai colori neutri', 'Adattatore elettrico Type G', 'Binocolo', 'Scarpe comode chiuse', 'Costume da bagno e sandali', 'Torcia o lampada frontale', 'Macchina fotografica e batteria di riserva'], included: ['Ingressi ai parchi indicati', 'Veicolo safari 4x4 con tettuccio apribile', 'Autista-guida locale', 'Pensione completa secondo l’itinerario', 'Acqua potabile durante i safari', 'Alloggio secondo l’itinerario', 'Trasferimenti hotel/aeroporto indicati'], excluded: ['Voli internazionali e nazionali', 'Visto', 'Assicurazione viaggio e medica', 'Mance e gratuità', 'Bevande alcoliche e premium', 'Spese personali e souvenir', 'Attività opzionali'], why: 'Un itinerario pensato per vivere paesaggi, fauna e cultura dell’Africa orientale con tempi equilibrati e assistenza locale.' },
  fr: { safari: 'Safari', days: 'jours', nights: 'nuit', morning: 'Matin', afternoon: 'Après-midi', overnight: 'Nuitée', packing: ['Crème solaire haute protection', 'Chapeau à larges bords', 'Répulsif anti-insectes', 'Vêtements légers aux couleurs neutres', 'Adaptateur électrique Type G', 'Jumelles', 'Chaussures fermées confortables', 'Maillot de bain et sandales', 'Lampe torche ou frontale', 'Appareil photo et batterie de rechange'], included: ['Entrées des parcs indiqués', 'Véhicule safari 4x4 à toit ouvrant', 'Chauffeur-guide local', 'Pension complète selon l’itinéraire', 'Eau potable pendant les safaris', 'Hébergement selon l’itinéraire', 'Transferts hôtel/aéroport indiqués'], excluded: ['Vols internationaux et domestiques', 'Frais de visa', 'Assurance voyage et médicale', 'Pourboires', 'Boissons alcoolisées et premium', 'Dépenses personnelles et souvenirs', 'Activités optionnelles'], why: 'Un itinéraire conçu pour découvrir les paysages, la faune et la culture de l’Afrique de l’Est à un rythme équilibré, avec une équipe locale.' },
  es: { safari: 'Safari', days: 'días', nights: 'noche', morning: 'Mañana', afternoon: 'Tarde', overnight: 'Alojamiento', packing: ['Protector solar de alta protección', 'Sombrero de ala ancha', 'Repelente de insectos', 'Ropa ligera de colores neutros', 'Adaptador eléctrico Tipo G', 'Prismáticos', 'Calzado cerrado cómodo', 'Bañador y sandalias', 'Linterna o frontal', 'Cámara y batería de repuesto'], included: ['Entradas a los parques indicados', 'Vehículo safari 4x4 con techo elevable', 'Conductor-guía local', 'Pensión completa según el itinerario', 'Agua potable durante los safaris', 'Alojamiento según el itinerario', 'Traslados indicados de hotel/aeropuerto'], excluded: ['Vuelos internacionales y nacionales', 'Visado', 'Seguro de viaje y médico', 'Propinas', 'Bebidas alcohólicas y premium', 'Gastos personales y recuerdos', 'Actividades opcionales'], why: 'Un itinerario diseñado para descubrir paisajes, fauna y cultura de África Oriental con un ritmo equilibrado y apoyo local.' },
  de: { safari: 'Safari', days: 'Tage', nights: 'Nacht', morning: 'Morgen', afternoon: 'Nachmittag', overnight: 'Übernachtung', packing: ['Sonnencreme mit hohem Lichtschutzfaktor', 'Sonnenhut', 'Insektenschutz', 'Leichte Kleidung in neutralen Farben', 'Steckeradapter Typ G', 'Fernglas', 'Bequeme geschlossene Schuhe', 'Badebekleidung und Sandalen', 'Taschen- oder Stirnlampe', 'Kamera und Ersatzakku'], included: ['Eintritte in die genannten Parks', '4x4-Safarifahrzeug mit Aufstelldach', 'Lokaler Fahrer-Guide', 'Vollpension gemäß Reiseplan', 'Trinkwasser während der Pirschfahrten', 'Unterkunft gemäß Reiseplan', 'Angegebene Hotel-/Flughafentransfers'], excluded: ['Internationale und Inlandsflüge', 'Visagebühren', 'Reise- und Krankenversicherung', 'Trinkgelder', 'Alkoholische und Premiumgetränke', 'Persönliche Ausgaben und Souvenirs', 'Optionale Aktivitäten'], why: 'Eine ausgewogene Reise durch Landschaften, Tierwelt und Kultur Ostafrikas mit lokaler Betreuung.' },
  ar: { safari: 'رحلة سفاري', days: 'أيام', nights: 'ليلة', morning: 'الصباح', afternoon: 'بعد الظهر', overnight: 'المبيت', packing: ['واقي شمس عالي الحماية', 'قبعة واسعة الحواف', 'طارد الحشرات', 'ملابس خفيفة بألوان محايدة', 'محول كهربائي من النوع G', 'منظار', 'أحذية مغلقة مريحة', 'ملابس سباحة وصنادل', 'مصباح يدوي', 'كاميرا وبطارية احتياطية'], included: ['رسوم دخول المتنزهات المذكورة', 'مركبة سفاري دفع رباعي بسقف قابل للفتح', 'سائق ومرشد محلي', 'إقامة كاملة حسب البرنامج', 'مياه للشرب أثناء رحلات السفاري', 'الإقامة حسب البرنامج', 'خدمات النقل المذكورة من الفندق أو المطار'], excluded: ['الرحلات الجوية الدولية والمحلية', 'رسوم التأشيرة', 'تأمين السفر والتأمين الطبي', 'الإكراميات', 'المشروبات الكحولية والمميزة', 'المصاريف الشخصية والهدايا', 'الأنشطة الاختيارية'], why: 'برنامج متوازن لاكتشاف المناظر الطبيعية والحياة البرية وثقافة شرق أفريقيا مع دعم محلي.' },
  zh: { safari: '野生动物之旅', days: '天', nights: '晚', morning: '上午', afternoon: '下午', overnight: '住宿', packing: ['高倍防晒霜', '宽檐帽', '驱虫剂', '浅色轻便服装', 'G型电源转换插头', '望远镜', '舒适的包头鞋', '泳衣和凉鞋', '手电筒或头灯', '相机和备用电池'], included: ['所列国家公园门票', '带开启式车顶的4x4越野车', '当地司机兼向导', '按行程提供全餐', '游戏驱车期间饮用水', '按行程安排住宿', '所列酒店/机场接送'], excluded: ['国际及国内航班', '签证费用', '旅行及医疗保险', '小费', '酒精及高级饮品', '个人消费和纪念品', '自费活动'], why: '以舒适节奏探索东非的自然景观、野生动物与文化，并由当地团队全程支持。' },
  sw: { safari: 'Safari', days: 'siku', nights: 'usiku', morning: 'Asubuhi', afternoon: 'Mchana', overnight: 'Malazi', packing: ['Mafuta ya kujikinga na jua', 'Kofia yenye ukingo mpana', 'Dawa ya kufukuza wadudu', 'Nguo nyepesi zenye rangi tulivu', 'Adapta ya umeme aina G', 'Darubini', 'Viatu vya kufunika miguu vilivyo vizuri', 'Nguo za kuogelea na sandal', 'Tochi au taa ya kichwani', 'Kamera na betri ya ziada'], included: ['Ada za kuingia katika hifadhi zilizotajwa', 'Gari la safari 4x4 lenye paa linalofunguka', 'Dereva-mwongoza wa eneo', 'Chakula kamili kulingana na ratiba', 'Maji ya kunywa wakati wa safari', 'Malazi kulingana na ratiba', 'Usafiri uliotajwa wa hoteli/uwanja wa ndege'], excluded: ['Ndege za kimataifa na ndani', 'Ada za visa', 'Bima ya safari na matibabu', 'Bakshishi', 'Vinywaji vya pombe na vya premium', 'Matumizi binafsi na zawadi', 'Shughuli za hiari'], why: 'Ratiba iliyosawazishwa ya kugundua mandhari, wanyamapori na utamaduni wa Afrika Mashariki kwa msaada wa timu ya eneo.' }
};

function localizePark(name: string, locale: SafariLocale) {
  return destinationNames[locale][name] ?? name;
}

export function getLocalizedSafari(safari: Safari, locale: SafariLocale): LocalizedSafari {
  if (locale === 'en') return safari;
  const c = copy[locale];
  const parks = safari.parks.map((p) => localizePark(p, locale));
  const name = `${safari.days}-${c.safari} — ${parks.join(' & ')}`;
  const itinerary = safari.itinerary.map((day, index) => ({
    day: `${c.safari} ${index + 1}`,
    title: `${parks.join(' & ')}`,
    morning: `${c.morning}: ${c.why}`,
    afternoon: `${c.afternoon}: ${c.why}`,
    overnight: `${c.overnight}: ${safari.lodges[index] ?? safari.lodges[safari.lodges.length - 1] ?? parks.join(' & ')}`
  }));
  return {
    ...safari,
    name,
    tagline: c.why,
    parks,
    highlights: parks.map((park) => `${c.safari} — ${park}`),
    itinerary,
    packingTips: c.packing,
    included: c.included,
    excluded: c.excluded
  };
}
