import type { Safari } from '@/lib/tours-data';

const packingTips = [
  'High SPF sunscreen (50+)', 'Wide-brim hat', 'Light long-sleeved clothing in neutral colours',
  'Comfortable closed-toe shoes', 'Binoculars', 'Camera with spare battery',
  'English 3-pin plug adapter (Type G)', 'Small torch/headlamp',
  'NO DRONES — strictly prohibited in national parks',
];

const included = [
  'KWS park entry fees', '4x4 safari vehicle with pop-up roof',
  'Professional driver-guide', 'Full board as per itinerary',
  'Drinking water during game drives', 'Accommodation as per itinerary',
  'Hotel/resort pickup and drop-off',
];
const excluded = [
  'International and domestic flights', 'Visa fees', 'Travel and medical insurance',
  'Tips and gratuities', 'Alcoholic and premium drinks', 'Personal expenses',
  'Optional activities',
];

type P = Omit<Safari, 'rating' | 'reviewCount' | 'itinerary' | 'packingTips'> & {
  itinerary: Safari['itinerary'];
};
const day = (n: number, title: string, morning: string, afternoon: string, overnight: string) => ({ day: `Day ${n}`, title, morning, afternoon, overnight });
const base = (p: P): Safari => ({ ...p, rating: 0, reviewCount: 0, packingTips, included, excluded });

export const safariCatalogueAdditions: Safari[] = [
  base({id:'1-day-tsavo-east',name:'1-Day Tsavo East Safari',tagline:'A full day in Kenya’s red-elephant wilderness',days:1,nights:0,parks:['Tsavo East'],lodges:['Day safari — no overnight'],tabs:['tsavo'],image:'/images/safaris/safari-experience-tsavo.jpg',category:'short',activityLevel:3,comfortLevel:2,popular:false,highlights:['Red elephants','Mudanda Rock','Aruba Dam','Voi River wildlife'],itinerary:[day(1,'Watamu → Tsavo East → Watamu','Early departure from Watamu and entry into Tsavo East for a morning game drive.','Continue through the Voi Plains, Mudanda Rock and Aruba Dam before the return journey to Watamu.','Return to Watamu — no overnight stay.')] }),
  base({id:'2-day-tsavo-west',name:'2-Day Tsavo West Safari',tagline:'Volcanic landscapes, springs and classic Tsavo wildlife',days:2,nights:1,parks:['Tsavo West'],lodges:['Kilaguni Serena Safari Lodge','Ngulia Safari Lodge'],tabs:['tsavo'],image:'/images/safaris/safari-simba-timon.jpg',category:'short',activityLevel:3,comfortLevel:4,highlights:['Mzima Springs','Shetani Lava Flow','Rhino Sanctuary','Chyulu Hills views'],itinerary:[day(1,'Watamu → Tsavo West','Drive from Watamu to Tsavo West and enter the park for a game drive.','Visit Mzima Springs and continue through volcanic landscapes in search of elephants, buffalo and predators.','Selected Tsavo West lodge/camp'),day(2,'Tsavo West → Watamu','Sunrise game drive through the western sector of the park.','Visit a scenic viewpoint or lava landscape before returning to Watamu.','Return to Watamu')] }),
  base({id:'3-day-tsavo-west-east',name:'3-Day Tsavo West & Tsavo East Safari',tagline:'From volcanic hills to the red-dust plains of Tsavo',days:3,nights:2,parks:['Tsavo West','Tsavo East'],lodges:['Kilaguni Serena Safari Lodge','Voi Wildlife Lodge'],tabs:['tsavo'],image:'/images/safaris/safari-simba-timon.jpg',category:'short',activityLevel:3,comfortLevel:4,highlights:['Mzima Springs','Shetani Lava Flow','Red elephants','Mudanda Rock'],itinerary:[day(1,'Watamu → Tsavo West','Travel from Watamu to Tsavo West and settle in before an afternoon game drive.','Explore the western plains and volcanic scenery.','Selected Tsavo West lodge/camp'),day(2,'Tsavo West → Tsavo East','Morning visit to Mzima Springs followed by a cross-park transfer.','Afternoon game drive in Tsavo East around the Voi Plains.','Voi Wildlife Lodge or selected camp'),day(3,'Tsavo East → Watamu','Sunrise game drive around Mudanda Rock and Aruba Dam.','Return to Watamu after breakfast.','Return to Watamu')] }),
  base({id:'4-day-tsavo-east-west',name:'4-Day Tsavo East & Tsavo West Safari',tagline:'Four days across Kenya’s iconic Tsavo wilderness',days:4,nights:3,parks:['Tsavo East','Tsavo West'],lodges:['Voi Wildlife Lodge','Kilaguni Serena Safari Lodge'],tabs:['tsavo'],image:'/images/safaris/safari-inside-tsavo-amboseli.jpg',category:'medium',activityLevel:3,comfortLevel:4,highlights:['Mudanda Rock','Aruba Dam','Mzima Springs','Shetani Lava Flow'],itinerary:[day(1,'Watamu → Tsavo East','Early drive from Watamu and enter Tsavo East.','Afternoon game drive on the Voi Plains.','Voi Wildlife Lodge or selected camp'),day(2,'Full Day Tsavo East','Sunrise drive around Mudanda Rock and Aruba Dam.','Extended wildlife drive through the eastern sector.','Voi Wildlife Lodge or selected camp'),day(3,'Tsavo East → Tsavo West','Morning drive before crossing toward Tsavo West.','Explore Mzima Springs and the volcanic western sector.','Kilaguni Serena Safari Lodge or selected camp'),day(4,'Tsavo West → Watamu','Final sunrise game drive.','Return to the coast via the scenic Tsavo landscape.','Return to Watamu')] }),
  base({id:'2-day-amboseli',name:'2-Day Amboseli Safari',tagline:'Elephants beneath the great Kilimanjaro',days:2,nights:1,parks:['Amboseli'],lodges:['AA Lodge Amboseli','Sentrim Amboseli'],tabs:['amboseli'],image:'/images/safaris/safari-inside-tsavo-amboseli.jpg',category:'short',activityLevel:2,comfortLevel:4,highlights:['Mount Kilimanjaro views','Large elephant herds','Observation Hill','Amboseli swamps'],itinerary:[day(1,'Watamu → Amboseli','Travel from the coast to Amboseli and check in.','Afternoon game drive through the swamps and open plains.','Selected Amboseli lodge/camp'),day(2,'Amboseli → Watamu','Sunrise game drive with Kilimanjaro views and elephant herds.','Breakfast followed by the return journey to Watamu.','Return to Watamu')] }),
  base({id:'3-day-amboseli',name:'3-Day Amboseli Safari',tagline:'Wildlife, wetlands and Kilimanjaro landscapes',days:3,nights:2,parks:['Amboseli'],lodges:['AA Lodge Amboseli','Sentrim Amboseli'],tabs:['amboseli'],image:'/images/safaris/safari-inside-tsavo-amboseli.jpg',category:'short',activityLevel:2,comfortLevel:4,highlights:['Kilimanjaro sunrise','Elephant herds','Observation Hill','Birdlife'],itinerary:[day(1,'Watamu → Amboseli','Coastal departure and transfer to Amboseli.','First afternoon game drive.','Selected Amboseli lodge/camp'),day(2,'Full Day Amboseli','Early game drive through the Amboseli wetlands.','Picnic or lodge lunch followed by an afternoon wildlife drive.','Selected Amboseli lodge/camp'),day(3,'Amboseli → Watamu','Final sunrise game drive.','Return to Watamu after breakfast.','Return to Watamu')] }),
  base({id:'4-day-amboseli-tsavo',name:'4-Day Amboseli & Tsavo Safari',tagline:'Kilimanjaro horizons and the red-dust elephants of Tsavo',days:4,nights:3,parks:['Amboseli','Tsavo East'],lodges:['AA Lodge Amboseli','Voi Wildlife Lodge'],tabs:['amboseli','tsavo'],image:'/images/safaris/safari-simba-timon.jpg',category:'medium',activityLevel:3,comfortLevel:4,highlights:['Kilimanjaro','Amboseli elephants','Mudanda Rock','Aruba Dam'],itinerary:[day(1,'Watamu → Amboseli','Transfer from Watamu to Amboseli.','Afternoon game drive under Kilimanjaro.','Selected Amboseli lodge/camp'),day(2,'Full Day Amboseli','Sunrise game drive and Observation Hill.','Extended wildlife drive through the wetlands and plains.','Selected Amboseli lodge/camp'),day(3,'Amboseli → Tsavo East','Morning wildlife drive then transfer to Tsavo East.','Afternoon game drive around the Voi Plains.','Voi Wildlife Lodge or selected camp'),day(4,'Tsavo East → Watamu','Sunrise drive around Mudanda Rock or Aruba Dam.','Return to Watamu.','Return to Watamu')] }),
  base({id:'2-day-taita-hills',name:'2-Day Taita Hills Wildlife Sanctuary Safari',tagline:'Mountain forest, wildlife and the famous Salt Lick waterhole',days:2,nights:1,parks:['Taita Hills'],lodges:['Salt Lick Safari Lodge'],tabs:['taita'],image:'/images/safaris/safari-nala-taita.jpg',category:'short',activityLevel:3,comfortLevel:4,highlights:['Salt Lick waterhole','Taita Hills scenery','Night wildlife viewing','Birdlife'],itinerary:[day(1,'Watamu → Taita Hills','Travel from Watamu to Taita Hills Wildlife Sanctuary.','Afternoon game drive followed by waterhole viewing at Salt Lick.','Salt Lick Safari Lodge'),day(2,'Taita Hills → Watamu','Early game drive through the sanctuary.','Return to Watamu after breakfast.','Return to Watamu')] }),
  base({id:'4-day-taita-hills-tsavo',name:'4-Day Taita Hills & Tsavo Safari',tagline:'A deeper journey through Taita Hills and Tsavo',days:4,nights:3,parks:['Taita Hills','Tsavo East','Tsavo West'],lodges:['Salt Lick Safari Lodge','Voi Wildlife Lodge','Kilaguni Serena Safari Lodge'],tabs:['taita','tsavo'],image:'/images/safaris/safari-nala-taita.jpg',category:'medium',activityLevel:3,comfortLevel:4,highlights:['Salt Lick waterhole','Red elephants','Mzima Springs','Tsavo landscapes'],itinerary:[day(1,'Watamu → Taita Hills','Travel to Taita Hills Wildlife Sanctuary.','Afternoon game drive and waterhole viewing.','Salt Lick Safari Lodge'),day(2,'Taita Hills → Tsavo East','Morning sanctuary drive.','Transfer to Tsavo East and afternoon game drive.','Voi Wildlife Lodge or selected camp'),day(3,'Tsavo East → Tsavo West','Sunrise game drive in Tsavo East.','Cross to Tsavo West and visit Mzima Springs.','Kilaguni Serena Safari Lodge or selected camp'),day(4,'Tsavo West → Watamu','Final game drive in Tsavo West.','Return to Watamu.','Return to Watamu')] }),
  base({id:'4-day-masai-mara',name:'4-Day Masai Mara Safari',tagline:'More time for big cats, open plains and the Mara River',days:4,nights:3,parks:['Masai Mara'],lodges:['Sentrim Mara','Manyatta Camp'],tabs:['mara'],image:'/images/safaris/safari-zazu.jpg',category:'medium',activityLevel:3,comfortLevel:4,highlights:['Big Five','Mara River','Great Migration season','Maasai culture'],itinerary:[day(1,'Watamu → Masai Mara','Flight or road transfer from the coast to the Mara.','Check in and enjoy an afternoon game drive.','Sentrim Mara or Manyatta Camp'),day(2,'Full Day Masai Mara','Early game drive across the Mara plains.','Full wildlife day with a picnic lunch and optional cultural visit.','Sentrim Mara or Manyatta Camp'),day(3,'Full Day Masai Mara','Sunrise predator viewing and wildlife tracking.','Continue through different sectors of the reserve.','Sentrim Mara or Manyatta Camp'),day(4,'Masai Mara → Watamu','Final sunrise game drive.','Transfer back to the coast.','Return to Watamu')] }),
  base({id:'2-day-lake-nakuru',name:'2-Day Lake Nakuru Safari',tagline:'Rhinos, Rift Valley scenery and a legendary bird lake',days:2,nights:1,parks:['Lake Nakuru'],lodges:['Milimani Hotel Nakuru','Selected Nakuru lodge'],tabs:['mara'],image:'/images/safaris/safari-tumbili.jpg',category:'short',activityLevel:2,comfortLevel:3,highlights:['White rhino','Black rhino habitat','Lake Nakuru','Rift Valley viewpoints'],itinerary:[day(1,'Watamu → Lake Nakuru','Travel inland from the coast through the Great Rift Valley.','Afternoon game drive around Lake Nakuru National Park.','Selected Nakuru lodge/hotel'),day(2,'Lake Nakuru → Watamu','Sunrise game drive for rhino and birdlife.','Return to Watamu after breakfast.','Return to Watamu')] }),
  base({id:'3-day-lake-nakuru-mara',name:'3-Day Lake Nakuru & Masai Mara Safari',tagline:'Rhino country followed by the legendary Mara plains',days:3,nights:2,parks:['Lake Nakuru','Masai Mara'],lodges:['Milimani Hotel Nakuru','Sentrim Mara'],tabs:['mara'],image:'/images/safaris/safari-tumbili.jpg',category:'short',activityLevel:3,comfortLevel:4,highlights:['Rhino sanctuary','Great Rift Valley','Mara Big Five','Mara River'],itinerary:[day(1,'Watamu → Lake Nakuru','Drive through the Rift Valley to Nakuru.','Afternoon wildlife drive around the lake and rhino sanctuary.','Milimani Hotel Nakuru or selected lodge'),day(2,'Lake Nakuru → Masai Mara','Morning Nakuru game drive.','Transfer to Masai Mara and afternoon game drive on arrival.','Sentrim Mara or Manyatta Camp'),day(3,'Masai Mara → Watamu','Dawn game drive before the return transfer.','Return to Watamu coast.','Return to Watamu')] }),
  base({id:'2-day-naivasha-hells-gate',name:'2-Day Lake Naivasha & Hell’s Gate Safari',tagline:'Rift Valley lakes, cycling and dramatic volcanic scenery',days:2,nights:1,parks:['Lake Naivasha','Hell’s Gate National Park'],lodges:['Selected Naivasha lodge'],tabs:['mara'],image:'/images/safaris/safari-tumbili.jpg',category:'short',activityLevel:3,comfortLevel:3,highlights:['Lake Naivasha boat ride','Hell’s Gate cliffs','Cycling or walking','Rift Valley scenery'],itinerary:[day(1,'Watamu → Lake Naivasha','Travel to the Great Rift Valley and Lake Naivasha.','Boat excursion or lakeside wildlife experience.','Selected Naivasha lodge'),day(2,'Hell’s Gate → Watamu','Explore Hell’s Gate by guided walk or cycling where available.','Return journey to Watamu.','Return to Watamu')] }),
  base({id:'4-day-naivasha-nakuru-mara',name:'4-Day Lake Naivasha, Lake Nakuru & Masai Mara Safari',tagline:'A classic Rift Valley and Mara combination',days:4,nights:3,parks:['Lake Naivasha','Lake Nakuru','Masai Mara'],lodges:['Selected Naivasha lodge','Milimani Hotel Nakuru','Sentrim Mara'],tabs:['mara'],image:'/images/safaris/safari-zazu.jpg',category:'medium',activityLevel:3,comfortLevel:4,highlights:['Hell’s Gate','Lake Nakuru rhinos','Mara Big Five','Great Rift Valley'],itinerary:[day(1,'Watamu → Lake Naivasha','Travel inland to Lake Naivasha.','Boat ride or Hell’s Gate experience.','Selected Naivasha lodge'),day(2,'Naivasha → Lake Nakuru','Morning lakeside experience.','Transfer to Nakuru and afternoon game drive.','Milimani Hotel Nakuru or selected lodge'),day(3,'Lake Nakuru → Masai Mara','Morning rhino and wildlife drive.','Transfer to Masai Mara and late afternoon game drive.','Sentrim Mara or Manyatta Camp'),day(4,'Masai Mara → Watamu','Sunrise game drive.','Return to Watamu.','Return to Watamu')] }),
  base({id:'5-day-mara-nakuru-amboseli',name:'5-Day Masai Mara, Lake Nakuru & Amboseli Safari',tagline:'Three of Kenya’s signature wildlife landscapes in one journey',days:5,nights:4,parks:['Masai Mara','Lake Nakuru','Amboseli'],lodges:['Sentrim Mara','Milimani Hotel Nakuru','AA Lodge Amboseli'],tabs:['mara','amboseli'],image:'/images/safaris/safari-tembo.jpg',category:'medium',activityLevel:4,comfortLevel:4,highlights:['Mara Big Five','Lake Nakuru rhinos','Kilimanjaro views','Elephant herds'],itinerary:[day(1,'Watamu → Masai Mara','Flight or road transfer from the coast.','Afternoon Mara game drive.','Sentrim Mara or Manyatta Camp'),day(2,'Full Day Masai Mara','Full-day wildlife drive with picnic lunch.','Continue tracking big cats and other Mara wildlife.','Sentrim Mara or Manyatta Camp'),day(3,'Masai Mara → Lake Nakuru','Dawn game drive then transfer toward the Rift Valley.','Afternoon Lake Nakuru game drive.','Milimani Hotel Nakuru or selected lodge'),day(4,'Lake Nakuru → Amboseli','Morning Nakuru drive.','Transfer to Amboseli and afternoon game drive.','AA Lodge Amboseli or selected camp'),day(5,'Amboseli → Watamu','Sunrise game drive with Kilimanjaro views.','Return to Watamu.','Return to Watamu')] }),
];
