'use client';

import { useMemo, useState } from 'react';
import { Mail, Phone, Search, Users } from 'lucide-react';
import AdminShell from '@/components/admin/AdminShell';
import { formatKES, guests, safeDate, useAdminData } from '@/components/admin/useAdminData';

export default function TravelersPage(){const {reservations,stats,loading}=useAdminData();const [q,setQ]=useState('');const [selected,setSelected]=useState<string|null>(null);
 const travelers=useMemo(()=>{const map=new Map<string,{key:string;first:string;last:string;email:string;phone:string;nationality:string;bookings:any[];spend:number}>();reservations.forEach(b=>{const key=(b.email||b.whatsapp||`${b.first_name}-${b.last_name}`).toLowerCase();const cur=map.get(key)||{key,first:b.first_name||'',last:b.last_name||'',email:b.email||'',phone:b.whatsapp||'',nationality:b.nationality||'',bookings:[],spend:0};cur.bookings.push(b);cur.spend+=Number(b.total_price||0);if(!cur.email)cur.email=b.email||'';if(!cur.phone)cur.phone=b.whatsapp||'';if(!cur.nationality)cur.nationality=b.nationality||'';map.set(key,cur)});return [...map.values()].filter(t=>[t.first,t.last,t.email,t.phone,t.nationality].join(' ').toLowerCase().includes(q.toLowerCase())).sort((a,b)=>b.bookings.length-a.bookings.length)},[reservations,q]);const traveler=travelers.find(t=>t.key===selected);
 return <AdminShell title="Travelers" badge={stats?.pending}><div className="space-y-5"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan-700">Customer management</p><h2 className="text-2xl font-bold">Travelers</h2><p className="text-sm text-slate-500">Unified traveler profiles built from your reservation history.</p></div><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border bg-white p-5"><Users className="h-5 w-5 text-cyan-700"/><p className="mt-4 text-xs text-slate-500">Unique travelers</p><p className="text-2xl font-bold">{travelers.length}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-xs text-slate-500">Total guests</p><p className="mt-4 text-2xl font-bold">{reservations.reduce((n,b)=>n+guests(b),0)}</p></div><div className="rounded-2xl border bg-white p-5"><p className="text-xs text-slate-500">Traveler revenue</p><p className="mt-4 text-2xl font-bold">{formatKES(reservations.reduce((n,b)=>n+Number(b.total_price||0),0))}</p></div></div><div className="rounded-2xl border bg-white shadow-sm"><div className="border-b p-4"><div className="relative max-w-xl"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search traveler name, email, phone or nationality..." className="w-full rounded-xl border bg-slate-50 py-2.5 pl-9 pr-3 text-sm"/></div></div><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3">{loading?<p className="col-span-full py-12 text-center text-sm text-slate-400">Loading travelers...</p>:travelers.map(t=><button key={t.key} onClick={()=>setSelected(t.key)} className="rounded-xl border p-4 text-left hover:border-cyan-200 hover:bg-cyan-50/20"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-cyan-100 font-bold text-cyan-700">{(t.first||t.last||'?').slice(0,1).toUpperCase()}</div><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-semibold">{t.bookings.length} booking{t.bookings.length===1?'':'s'}</span></div><p className="mt-3 font-semibold">{t.first} {t.last}</p><p className="mt-1 truncate text-xs text-slate-500">{t.email||t.phone||'No contact'}</p><p className="mt-2 text-xs text-slate-400">{t.nationality||'Nationality not recorded'}</p><p className="mt-3 text-sm font-semibold">{formatKES(t.spend)}</p></button>)}</div></div></div>
 {traveler&&<div className="fixed inset-0 z-[60] bg-slate-950/40 p-4" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="mx-auto mt-10 max-h-[80vh] max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h3 className="text-xl font-bold">{traveler.first} {traveler.last}</h3><p className="text-sm text-slate-500">Traveler profile</p></div><button onClick={()=>setSelected(null)} className="text-slate-400">Close</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><p className="rounded-xl bg-slate-50 p-3 text-sm"><Mail className="mr-2 inline h-4 w-4"/>{traveler.email||'—'}</p><p className="rounded-xl bg-slate-50 p-3 text-sm"><Phone className="mr-2 inline h-4 w-4"/>{traveler.phone||'—'}</p></div><h4 className="mt-6 font-semibold">Reservation history</h4><div className="mt-3 space-y-2">{traveler.bookings.map(b=><div key={b.id} className="flex items-center justify-between rounded-xl border p-3"><div><p className="text-sm font-semibold">{b.safari_name||'Custom Safari'}</p><p className="text-xs text-slate-500">{safeDate(b.arrival_date)} · {b.reservation_status}</p></div><span className="text-sm font-semibold">{formatKES(b.total_price)}</span></div>)}</div></div></div>}</AdminShell>}
